name: ethiopian_datetime
description: Dart / Flutter Package for Ethiopian Calendar and dateFormatting and more utilties.
version: 1.0.2
repository: https://github.com/rarksule/ethiopian_datetime.git

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: '>=0.17.0 <0.20.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
