const ethiopianDateSymbols = {
  "ti": {
    "ERAS": ["BC", "AD"],
    "ERANAMES": ["Before Christ", "Anno Domini"],
    "NARROWMONTHS": [
      "መ",
      "ጥ",
      "ሕ",
      "ታ",
      "ጥ",
      "የ",
      "መ",
      "ሚ",
      "ጉ",
      "ሰ",
      "ሓ",
      "ነ",
      "ጳ",
    ],
    "MONTHS": [
      "መስከረም",
      "ጥቅምቲ",
      "ሕዳር",
      "ታሕሳስ",
      "ጥሪ",
      "የካቲት",
      "መጋቢት",
      "ሚያዝያ",
      "ጉንበት",
      "ሰነ",
      "ሓምለ",
      "ነሓሰ",
      "ጳጉሜን",
    ],
    "SHORTMONTHS": [
      "መስከ",
      "ጥቅም",
      "ሕዳር",
      "ታሕሳ",
      "ጥሪ",
      "የካቲ",
      "መጋቢ",
      "ሚያዝ",
      "ጉንበ",
      "ሰነ",
      "ሓምለ",
      "ነሓሰ",
      "ጳጉሜ",
    ],
    "WEEKDAYS": [
      "ሶኒ",
      "ሰሉስ",
      "ረቡዕ",
      "ሓሙስ",
      "ዓርቢ",
      "ቀዳም",
      "ሰንበት",
    ],
    "SHORTWEEKDAYS": [
      "ሶኒ",
      "ሰሉስ",
      "ረቡዕ",
      "ሓሙስ",
      "ዓርቢ",
      "ቀዳም",
      "ሰንበ",
    ],
    "NARROWWEEKDAYS": [
      "ሶ",
      "ሰ",
      "ረ",
      "ሓ",
      "ዓ",
      "ቀ",
      "ሰ",
    ],
    "QEN": ['መዐልቲ'],
    "MATA": ['ምሸት'],
    "LELIT": ['ለሊት'],
    "TEWAT": ['ጉሓት'],
    'SEAT': ["ሰአት"]
  },
  "am": {
    "ERAS": ["ዐ.ዐ", "ዐ.ል"],
    "ERANAMES": ["ዐመተ ዐለም", "ዐመተ ልደት"],
    "NARROWMONTHS": [
      "መ",
      "ጥ",
      "ህ",
      "ታ",
      "ጥ",
      "የ",
      "መ",
      "ሚ",
      "ግ",
      "ሰ",
      "ሐ",
      "ነ",
      "ጳ"
    ],
    "MONTHS": [
      "መስከረም",
      "ጥቅምት",
      "ሕዳር",
      "ታሕሣስ",
      "ጥር",
      "የካቲት",
      "መጋቢት",
      "ሚያዚያ",
      "ግንቦት",
      "ሰኔ",
      "ሐምሌ",
      "ነሐሴ",
      "ጳጉሜ"
    ],
    "SHORTMONTHS": [
      "መስከ",
      "ጥቅም",
      "ሕዳር",
      "ታሕሣ",
      "ጥር",
      "የካቲ",
      "መጋቢ",
      "ሚያዚ",
      "ግንቦ",
      "ሰኔ",
      "ሐምሌ",
      "ነሐሴ",
      "ጳጉሜ"
    ],
    "WEEKDAYS": ["ሰኞ", "ማክሰኞ", "ረቡዕ", "ሐሙስ", "ዓርብ", "ቅዳሜ", "እሁድ"],
    "SHORTWEEKDAYS": ["ሰኞ", "ማክሰ", "ረቡዕ", "ሐሙስ", "ዓርብ", "ቅዳሜ", "እሁድ"],
    "NARROWWEEKDAYS": ["ሰ", "ማ", "ረ", "ሐ", "ዓ", "ቅ", "እ"],
    "QEN": ['ቀን'],
    "MATA": ['ማታ'],
    "LELIT": ['ለሊት'],
    "TEWAT": ['ጠዋት'],
    'SEAT': ["ሰአት"]
  },
  "om": {
    "ERAS": ["BC", "AD"],
    "ERANAMES": ["Before Christ", "Anno Domini"],
    "NARROWMONTHS": [
      "F",
      "I",
      "S",
      "M",
      "A",
      "G",
      "B",
      "E",
      "C",
      "W",
      "A",
      "H",
      "Q",
    ],
    "MONTHS": [
      "Fulbaana",
      "Inkoloolessa",
      "Sadaasa",
      "Muddee",
      "Amajjii",
      "Guraandhala",
      "Bitootessa",
      "Ebla",
      "Caamsaa",
      "Waxabajjii",
      "Adoolessa",
      "Hagayya",
      "Qaammee",
    ],
    "SHORTMONTHS": [
      "Ful",
      "Ink",
      "Sad",
      "Mud",
      "Ama",
      "Gur",
      "Bit",
      "Ebl",
      "Caa",
      "Wax",
      "Ado",
      "Hag",
      "Qaa",
    ],
    "WEEKDAYS": [
      "Wiixata",
      "Kibxata",
      "Roobii",
      "Kamisa",
      "Jimaata",
      "Sanbata",
      "Dilbata",
    ],
    "SHORTWEEKDAYS": [
      "Wii",
      "Kib",
      "Roo",
      "Kam",
      "Jim",
      "San",
      "Dil",
    ],
    "NARROWWEEKDAYS": [
      "W",
      "K",
      "R",
      "K",
      "J",
      "S",
      "D",
    ],
    "QEN": ['Guyya'],
    "MATA": ['Galgala'],
    "LELIT": ['Haalkan'],
    "TEWAT": ['Ganama'],
    'SEAT': ["sa'a"]
  },
  "so": {
    "ERAS": ["BC", "AD"],
    "ERANAMES": ["Before Christ", "Anno Domini"],
    "NARROWMONTHS": [
      "S",
      "O",
      "N",
      "D",
      "J",
      "F",
      "M",
      "A",
      "L",
      "J",
      "J",
      "O",
      "P",
    ],
    "MONTHS": [
      "Sebtembar",
      "Oktoobar",
      "Nofeembar",
      "December",
      "Janaayo",
      "Febraayo",
      "Maarso",
      "Abriil",
      "Laga yaabaa",
      "Juun",
      "Julaay",
      "Ogosto",
      "Pagume",
    ],
    "SHORTMONTHS": [
      "Seb",
      "Okt",
      "Nof",
      "Dec",
      "Jan",
      "Feb",
      "Maa",
      "Abr",
      "Lag",
      "Juu",
      "Jul",
      "Ogo",
      "Pag",
    ],
    "WEEKDAYS": [
      "Isniin",
      "Talaado",
      "Arbacada",
      "Khamiis",
      "Jimcaha",
      "Sabti",
      "Axad",
    ],
    "SHORTWEEKDAYS": [
      "Isn",
      "Tal",
      "Arb",
      "Kha",
      "Jim",
      "Sab",
      "Axa",
    ],
    "NARROWWEEKDAYS": [
      "I",
      "T",
      "A",
      "K",
      "J",
      "S",
      "A",
    ],
    "QEN": ['maalin'],
    "MATA": ['habeen'],
    "LELIT": ['saqdhaxe'],
    "TEWAT": ['aroorti'],
    'SEAT': ["saac"]
  },
  "en": {
    "ERAS": ["BC", "AD"],
    "ERANAMES": ["Before Christ", "Anno Domini"],
    "NARROWMONTHS": [
      "M",
      "T",
      "H",
      "T",
      "T",
      "Y",
      "M",
      "M",
      "G",
      "S",
      "H",
      "N",
      "P",
    ],
    "MONTHS": [
      "Meskerem",
      "Tikimt",
      "Hidar",
      "Tahsas",
      "Tir",
      "Yeatit",
      "Megabit",
      "Miyazya",
      "Ginbot",
      "Sene",
      "Hamle",
      "Nehase",
      "Pagume",
    ],
    "SHORTMONTHS": [
      "mesk",
      "Tik",
      "Hid",
      "Tahs",
      "Tir",
      "Yeka",
      "Mega",
      "Miya",
      "Gin",
      "Sen",
      "Ham",
      "Neh",
      "Pag",
    ],
    "WEEKDAYS": [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ],
    "SHORTWEEKDAYS": [
      'Mon',
      'Tue',
      'Wed',
      'Thu',
      'Fri',
      'Sat',
      'Sun',
    ],
    "NARROWWEEKDAYS": [
      'M',
      'T',
      'W',
      'T',
      'F',
      'S',
      'S',
    ],
    "QEN": ['Noon'],
    "MATA": ['Evening'],
    "LELIT": ['Night'],
    "TEWAT": ['Morning'],
    'SEAT': ["O'clock"]
  }
};

String etDateSymbol(String? locale, String key, int index, {String time = ""}) {
  if (index < 0) {
    if (locale == 'om') {
      return "${ethiopianDateSymbols[locale]![key]![0]} ${index == -1 ? ethiopianDateSymbols[locale ?? "am"]!['SEAT']![0] : ''} $time ";
    } else {
      return "${ethiopianDateSymbols[locale ?? "am"]![key]![0]} $time ${index == -1 ? ethiopianDateSymbols[locale ?? "am"]!['SEAT']![0] : ''}";
    }
  } else {
    return ethiopianDateSymbols[locale ?? "am"]![key]![index - 1];
  }
}
